target-version = "py313"

line-length = 88
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
select = [
    "B",    # flake8-bugbear
    "BLE",  # flake8-blind-except
    "C4",   # flake8-comprehensions
    "E",    # pycodestyle
    "F",    # Pyflakes
    "FIX",  # flake8-fixme
    "I",    # isort
    "PERF", # Perflint
    "PL",   # Pylint
    "RUF",  # Ruff-specific rules
    "S",    # flake8-bandit
    "SIM",  # flake8-simplify
    "UP",   # pyupgrade
]
ignore = [
    "E501",    # Avoid enforcing line-length violations (`E501`)
    "PLR0913", # Too many arguments in function definition (9 > 5)
    "FIX002",  # Line contains TODO or FIXME
    "C420",
]

[lint.isort]
force-single-line = true

[lint.flake8-bugbear]
extend-immutable-calls = [ # ignore B008 only for FastAPI dependency injection pattern
    "fastapi.Depends",
    "fastapi.Query",
    "fastapi.Path",
    "fastapi.Security",
    "fastapi.security.HTTPBearer",
]