name: Feature request
description: Suggest an idea for PySteg
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea? Check the [Roadmap](https://github.com/kisscool-fr/pysteg#roadmap) first to see if it is already planned.

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this solve, or what workflow would it improve?
      placeholder: I often need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you thought about?
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to open a pull request for this feature
          required: false
